### PR TITLE
Increase the test delays as they were before

### PR DESCRIPTION
**Pull request by badboywj**
The issue happened on 12-SP5 after updating the sleep time from the current master branch(commit: 1219b4b8d8766868e1762f7377459f7b196ef74a) in **ClusterLabs**
https://openqa.suse.de/tests/14048367#step/hawk_gui/82

and everything worked well after changing the sleep time back.

### CODE REVIEW

**Comment by aleksei-burlakov** [comment]
The word `revoke` is somewhat misleading without the context. If you look the git log, you will see that all previous commits have explanations. Could you please write it more explicitly, and more verbose like

```
Increase the test delays back, as they were before

The issue happened on <the upstream version XYZ> after updating the sleep time from the current master branch in ClusterLabs
https://openqa.suse.de/tests/14048367#step/hawk_gui/82

and everything worked well after changing the sleep time back.
```

**Comment by badboywj** [comment]
> The word `revoke` is somewhat misleading without the context. If you look the git log, you will see that all previous commits have explanations. Could you please write it more explicitly, and more verbose like
> 
> ```
> Increase the test delays back, as they were before
> 
> The issue happened on <the upstream version XYZ> after updating the sleep time from the current master branch in ClusterLabs
> https://openqa.suse.de/tests/14048367#step/hawk_gui/82
> 
> and everything worked well after changing the sleep time back.
> ```

Good suggestion, I have updated the PR title and description, thank you :+1:

**Comment by alvarocarvajald** [comment]
> > The word `revoke` is somewhat misleading without the context. If you look the git log, you will see that all previous commits have explanations. Could you please write it more explicitly, and more verbose like
> > ```
> > Increase the test delays back, as they were before
> > 
> > The issue happened on <the upstream version XYZ> after updating the sleep time from the current master branch in ClusterLabs
> > https://openqa.suse.de/tests/14048367#step/hawk_gui/82
> > 
> > and everything worked well after changing the sleep time back.
> > ```
> 
> Good suggestion, I have updated the PR title and description, thank you 👍

I think @aleksei-burlakov meant to also change the commit message, as that's what is left in the repository log.

**Comment by badboywj** [comment]
> > I think @aleksei-burlakov meant to also change the commit message, as that's what is left in the repository log.
> 
> Thats right. It will make navigating through the log history easier.

I have updated commit message, please check it :smile:

**Pull request merged**
