### PR TITLE
Fix typo in index and login page title

### PR DESCRIPTION
**Pull request by thutterer**
Our designer might be Italian but the page titles probably shouldn't be :)

### CODE REVIEW

**Comment by tboerger** [comment]
These are anyway just the blueprints created by manuele. But ok...

**Comment by krig** [comment]
We should perhaps remove those blueprints from the repository now, what do you think? It's a bit confusing to keep them. Maybe push a branch that still has them, so anyone looking can still find them.

**Comment by tboerger** [comment]
Yeah sure

**Comment by krig** [comment]
Done.

**Pull request merged**
