### PR TITLE
Prometheus configuration

### PR DESCRIPTION
**Pull request by ayoub-belarbi**
In this pull request, we automate the configuration of the prometheus datasource in Grafana, and then deploying the JSON configuration for the HA dashboard. No intervention from the user is required once Salt provisioning is complete and the user should be able to see the dashboard on port 3999.

### CODE REVIEW

**Comment by diegoakechi** [comment]
Hi @ayoub-belarbi 
Have you considered to use the grafana state module of salt? I think it could be beneficial to make the configuration idempotent.
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.grafana.html

There is also a salt-formula for prometheus that maybe could be used too:

https://github.com/salt-formulas/salt-formula-prometheus

**Comment by krig** [comment]
Looks good to me, but I would also be interested in looking at the salt formulas for grafana and prometheus, maybe they can be useful :)

**Comment by ayoub-belarbi** [comment]
@diegoakechi @krig I looked into that before and forgot to use it later. I will take a look on that right now and see what I can update :+1:

**Comment by ayoub-belarbi** [comment]
Still working on this, since when trying to use the formula, I discovered that the Salt minion config is not read correctly.

**Comment by krig** [comment]
Woah, so much has changed!

**Pull request merged**
