### PR TITLE
Dev: Use configure delete without --force

### PR DESCRIPTION
**Pull request by liangxin1300**
Delete a running resource is dangerous

### CODE REVIEW

**Comment by krig** [comment]
The `--force` is there for a reason. The UI presents confirmation before deletion.

**Comment by liangxin1300** [comment]
Confirm message should include such as "resource XXX is running"

**Comment by krig** [comment]
Yeah, that's a good idea :)

Regarding configuration in Hawk, my plan is to redo it completely: The mode of editing is not good for a user interface like this.

I think the current wizards are too limited in their functionality as well, and they are not very flexible. My idea is to replace the current configuration functionality in Hawk with a modal system (edit, then apply) based on managing the cluster nodes using Salt.

We are also working on changing the Hawk backend to be compatible with pcs, so there will be major changes as a consequence.

So I would not recommend spending too much energy making improvements to the Hawk configuration interface. We plan to replace it.

**Comment by liangxin1300** [comment]
Sounds great!
Where is the repo? I want to join in:)

**Comment by krig** [comment]
You're welcome!

On the backend side, there is the API server project, here:
https://github.com/krig/hawk-apiserver

Currently it is only used as a proxy and for the long-running `/monitor` endpoint, but my idea is to eventually have the apiserver capable of serving a pure API without needing the Hawk Rails backend.

On the frontend side, @ayoub-belarbi and @bisht-richa are working on a client which is based on Vue.js here:
https://github.com/hawk-ui/hawk-web-client

If you want something to start looking at now, there is a known bug in the hawk-apiserver: There is a feature in `redirect.go` which detects if the user is trying to connect with HTTP to the HTTPS port, and redirects the user to HTTPS on the same port (making it a bit easier to for beginners to use Hawk).

With a new version of Chromium, it seems the detection sometimes fails because the client sends less than 6 bytes which is the minimum needed to differentiate HTTP and HTTPS. This doesn't seem to happen with Firefox. The first thing that is needed is to figure out exactly what the problem is. My hypothesis is that it is happening due to HTTP/2, but I need to study the protocol to see if that might be the cause.

**Comment by liangxin1300** [comment]
Wow, I need to learn go or Vue.js firstly :)
Anyway, I'm watching these projects from now.

BTW, I have two questions:
1. Do you mean scripts module in crmsh will also be replaced with salt?
2. How long the current hawk2's life cycle? Until 15sp2?

**Comment by krig** [comment]
1. Not decided yet. If we can do everything that the scripts module can do using salt, then maybe yes.
2. Not decided yet, also depends on how much progress we make and if the ideas work :)

**Pull request closed without merging**
