### PR TITLE
move simulator panel to the top

### PR DESCRIPTION
**Pull request by thutterer**
It's now in a better place than before for sure.
All my more fancy ideas would have broken the mobile views or made them way more complicated.
This is simple but OK I guess.

### CODE REVIEW

**Comment by krig** [comment]
Good idea! I think it is definitely an improvement over the previous version, but it feels like it can still be improved. For one thing, the yellow color of the warning panel is quite faded, it doesn't really give the sense of importance that I think it should have. Perhaps this is more a question for @manuelecarlini about tweaking the colors a bit.

Maybe if we combined this with changing the color of the top bar, perhaps.

**Comment by tboerger** [comment]
I still think a toggleable sidebar that is displayed initially makes most semse. I would just move the label that gets displayed while simulation should be moved to top nav, or as you said give the topnav another color

**Comment by tboerger** [comment]
Let's close that for now.

**Comment by thutterer** [comment]
As discussed with @tboerger we give this attempt another chance.
I rearranged the input elements a bit. Now it's more compact.

I still like this better than the fancy #56.
This here just fits better into Bootstrap's grid system and works the same on all screen widths.

**Comment by thutterer** [comment]
One piece is still missing: I have to save the toggle-state in the session. I will add this tomorrow.

**Comment by krig** [comment]
Your reasoning sounds good to me. My dream solution is still something more ambitious like replacing the top navbar with a special simulator control panel, especially for implementing the transaction features that we pushed forward. But for RC2, this sounds like the best option.

**Comment by krig** [comment]
OK, lets merge this, we can refine it later if necessary. Thanks!

(I guess one immediate refinement / addition could be to change the color of the header bar when in simulator mode)

**Pull request merged**
