### PR TITLE
allow adding rules to new location contraints

### PR DESCRIPTION
**Pull request by thutterer**
- fixes frontend issue

__Note:__
Alternatively we could always create an empty rule when showing this view for new constraints.
But then we would still need an add-button after the last rule (or reordering buttons).

### CODE REVIEW

**Comment by krig** [comment]
I think this should be OK for now. Thanks!

**Comment by tboerger** [comment]
Nooo, see comments on IRC

**Comment by tboerger** [comment]
This would look somehow fucked up

**Comment by thutterer** [comment]
@krig The idea of Thomas is more DRY. I will change it.

**Comment by krig** [comment]
Alright, I'll let you two work it out.

**Comment by tboerger** [comment]
Already pushed, look at https://github.com/ClusterLabs/hawk/commit/b061061069924ccdb91f7c9e86acb8629f3ab063

**Pull request closed without merging**
