### PR TITLE
Build: Update spec file for move from lighttpd to puma

### PR DESCRIPTION
**Pull request by krig**

### CODE REVIEW

**Comment by tboerger** [comment]
On the first look it seems to be fine. But in the near future we have to check if it's still building for various SUSE versions and Redhat.

**Comment by krig** [comment]
Yeah, the sysvinit scripts need to be fixed, and the rubygem handling probably doesn't work on RH.

**Comment by tboerger** [comment]
Exactly, but for the current development state you get my :+1:

**Comment by krig** [comment]
Alright, merging :)

**Pull request merged**
