### PR TITLE
Dev: Let error message shown in location/colocation/order page

### PR DESCRIPTION
**Pull request by liangxin1300**
Like how to handle error messages in primitives controller,
I let the error messages shown on the location/colocation/order page.
So, I have closed issues #118.

### CODE REVIEW

**Comment by liangxin1300** [comment]
append commit:   Dev: Strip redundant error messages(from errors.messages[:id])

Error messages like "ID ID is required", "ID Invalid ID", "Score Score is required" and "Score Invalid score value" are redundant

It's better to make it clear

Regards,
xin

**Comment by liangxin1300** [comment]
also append commit:   Dev: Let error message shown in group/clone/master page

**Comment by ayoub-belarbi** [comment]
@liangxin1300  Can you please explain why we need to create a RuntimeError?  I really didn't understand the purpose. All the errors are stored in @location.errors if @location.save fails (after validation), for example. The errors should be parsed and formatted using Javascript for example in the presentation layer and not in the controller.

**Comment by liangxin1300** [comment]
I use "RuntimeError" because @houndci-bot give me hints ---- "Lint/InheritException: Inherit from RuntimeError instead of Exception." : )

And, I created these commits because I've noticed that in primitives_controller, we just use this way to put error messages into the top of the page when save return false, then I think maybe the other controllers should do the same handle process.

**Comment by ayoub-belarbi** [comment]
> I use "RuntimeError" because @houndci-bot give me hints in #120 ---- "Lint/InheritException: Inherit from RuntimeError instead of Exception." : )
> 
> And, I created these commits because I've noticed that in primitives_controller, we just use this way to put error messages into the top of the page when save return false, then I think maybe the other controllers should do the same handle process.

Thanks for clarifying this :) So we have two options now, either removing this from both primitive_controller and location/colocation/order controllers and handling this in Javascript side or we keep it like this and we handle all the errors in this way. Any way your fix is much cleaner for the moment.

Thanks

**Comment by liangxin1300** [comment]
I think keep controller simple is right(handle this in JS),
and currently, it seems that the codes in controller to handle error are redundant;

maybe we have more spaces to improve that:)

**Pull request merged**
