### PR TITLE
some fixes for issues we found while testing

### PR DESCRIPTION
**Pull request by thutterer**

### CODE REVIEW

**Comment by tboerger** [comment]
IMHO the routes that doesnt match should result in a 404 page.

**Comment by thutterer** [comment]
removing the "wip" as the three commits are ready for review and I won't get anything else done today probably.

> IMHO the routes that doesn’t match should result in a 404 page.

yes, that would be better probably. but that would also need some design decisions. the routing to root was a one-liner. let's do the 404 page in a separate PR, ok?

**Comment by tboerger** [comment]
It should already display a 404 page in production environment :)

**Comment by thutterer** [comment]
When we tested in production two days ago, we only got a blank page saying `"An unhandled lowlevel error occured. The application logs may have details."` which is not a proper 404 page. looks more like a 500 to me.

**Comment by tboerger** [comment]
That sounds like another issue. The log is your friend :)

**Comment by krig** [comment]
@thutterer I also am not sure about pointing everything at the root in the routes, that doesn't look like the right solution. I think we do have a 404 page, it would be better to redirect there. I don't think Rails does this by default because it expects to have nginx or apache in front and during development you want the exception to bubble up through the router (so maybe turn that route off if in development?) but we're running it directly through puma.

**Comment by krig** [comment]
Maybe something like this? http://snippets.aktagon.com/snippets/344-custom-404-rails-error-pages

**Comment by thutterer** [comment]
> I think we do have a 404 page

Where is it? I cannot find it.

**Comment by krig** [comment]
In `hawk/public/404.html`. No idea if it looks OK :)

**Comment by thutterer** [comment]
Thanks. It's quite broken. I try to fix it and change that commit accordingly.

**Comment by krig** [comment]
Oh, BTW: I've already merged and pushed the three commits from this pull request to `master`. You should be able to rebase this PR on master and then force-push it, and then we can keep discussing further changes without losing the thread :)

**Comment by krig** [comment]
These are all merged now.

**Pull request closed without merging**
