### PR TITLE
 add e2e test for hawk

### PR DESCRIPTION
**Pull request by MalloZup**

### CODE REVIEW

**Comment by MalloZup** [comment]
@alvarocarvajald @ricardobranco777  any feedback on this? we can delete the gitlabrepo and you can maintain it here  directly.

let me knko

**Comment by alvarocarvajald** [comment]
> @alvarocarvajald @ricardobranco777 any feedback on this? we can delete the gitlabrepo and you can maintain it here directly.
> 
> let me know

Hello Dario.

LGTM. My only question would be with regards to the automatic publishing of the docker image that it's used on the openQA tests.

**Comment by MalloZup** [comment]
regarding that we can create a github action workflow which can publish the image when the docker File is modified.

**Comment by MalloZup** [comment]
follow-up https://github.com/ClusterLabs/hawk/issues/204

**Pull request merged**
